services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: .
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/chatDB
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - redis
      - rabbitmq

  nginx:
      build:
        context: ./nginx
      container_name: nginx
      ports:
        - "80:80"
      depends_on:
        - backend